## 文件保存 ##
dir=$HOME/Downloads
save-session=$HOME/.config/aria2/aria2.session
save-session-interval=60

## 下载连接 ##
# max-connection-per-server=8
max-connection-per-server=16
min-split-size=1M
# split=8
split=64
# max-concurrent-downloads=3
max-concurrent-downloads=5

## 性能优化 ##
disk-cache=64M
file-allocation=falloc

## 网络稳定性 ##
disable-ipv6=false
timeout=90
connect-timeout=60
max-tries=5
allow-overwrite=true

## 如果只用 HTTP/HTTPS 下载 ISO，关闭 BT
enable-dht=false
enable-peer-exchange=false

## 全局请求头
user-agent=Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0
header=Accept: */*
header=Accept-Language: en-US,en;q=0.9
header=Connection: keep-alive
